### ISSUE TITLE
Event handler to identify when the whole PDF and its pages have been scrolled

### ISSUE THREAD

**Issue by bernardoif** [vitalii-vov/Maui.PDFView#10]
Hi,

It would be nice if your library could trigger an event when detecting the scroll reached the last page.

Regards

**Comment by vitalii-vov** [comment]
Hi @bernardoif 
You can check the code in the [feature-pageChanged](https://github.com/vitalii-vov/Maui.PDFView/tree/feature-pageChanged) branch.

It has added support for iOS, Mac and Android.
I will release it after adding Windows and when I can test it working.

You can clone the repository for yourself to check it out or if you need it urgently.

**Comment by vitalii-vov** [comment]
Update 1.0.6 has been released. 
The PageChangedCommand has been added to it. 
See the example project for how to use the command.

**Comment by bernardoif** [comment]
Hi @vitalii-vov 

Thank you so much, I really appreciate the effort you put into this new feature
