### ISSUE TITLE
Handler not found for view Maui.PDFView.PdfView

### ISSUE THREAD

**Issue by vikashhd** [vitalii-vov/Maui.PDFView#11]
We are getting exception of Handler not found for view Maui.PDFView.PdfView in the latest version whereas it is working fine on 1.0.4. Kindly check

**Comment by vitalii-vov** [comment]
Hello,
Can you send StackTrace on the error? On which platform are you getting the exception?

**Comment by vitalii-vov** [comment]
@vikashhd any updates?
