### ISSUE TITLE
App crash while opening or closing the PDF viewer page

### ISSUE THREAD

**Issue by vikashhd** [vitalii-vov/Maui.PDFView#3]
Dear Team,
I have Maui blazor app in which I am pushing Xaml page which has Pdf Viewer. Sometime it crashes while loading pdf or sometimes when we are closing this page. It is happening randomly  for the same pdf. Sometimes work properly.
In visual studio I can see crash logs regarding Native Crash.
r/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a0fa0 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100395974 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100393540 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003621c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100309928 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10030fc24 - /private/
.
0x189a67040  81 00 00 54 4a 01 01 ca 4a 01 10 ca 2a 0e 1f d7  ...TJ...J...*...

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:UIApplicationMain <0x0006e>
	  at UIKit.UIApplication:Main <0x0015a>
	  at AppPdfTest.Program:Main <0x0002c>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0007e>
	  at <unknown> <0x00000>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00074>
	  at System.Reflection.MethodBaseInvoker:InterpretedInvoke_Method <0x00050>
	  at System.Reflection.MethodBaseInvoker:InvokeDirectByRefWithFewArgs <0x001e8>
	  at System.Reflection.MethodBaseInvoker:InvokeWithOneArg <0x002a4>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x001b6>
	  at System.Reflection.MethodBase:Invoke <0x0004e>
	  at Xamarin.iOS.HotRestart.Application:Ru
var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a0f68 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100395974 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100393540 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003621c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100309928 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100311360 - /privat
eFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x191bbb834 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bbb7c8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb92f8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb8484 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb7cd8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1d6a681a8 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1941f090c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1942a49d0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1000505f4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : xamarin_UIApplicationMain
	0x1003a2668 - /private/
	0x193dfdb44 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193dfdab8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193df6b10 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1932553b4 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x193254f38 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x1932b00e0 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x193225028 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19326ed7c - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x193e9fff4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9d76c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9d3b0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9e254 - /System/Library/Privat
	0x193dfdc3c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x100391de0 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10037cccc - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10035f04c - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1ee986e9c - /usr/lib/system/libsystem_platform.dylib : <redacted>

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

e/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1002cdfac - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1002d8648 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a2634 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a0fa0 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100395974 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100393540 - /priv
- /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1b5269e4c - /usr/lib/dyld : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x189a67020):0x189a67010  ea 03 00 aa 2a 5c ed f2 50 19 c1 da ef 03 10 aa  ....*\..P.......
0x189a67020  0b 0a 40 f9 eb 02 00 37 6a bd 40 92 2c 1c 41 ca  ..@....7j.@.,.A.
0x189a67030  8c c1 4b 8a 4d 11 0c 8b b1 25 ff a8 3f 01 01 eb  ..K.M....%..?..
ate/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003621c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100309928 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10030fc24 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003677c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10007c39c - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : xamarin_get_original_working_directory_path
	0x1003cfda0 
The app has been terminated.
var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003677c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10007c39c - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : xamarin_get_original_working_directory_path
	0x1003cfda0 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1b5269e4c - /usr/lib/dyld : <redacted>

Exiting early due to double fault.

containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003621c4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100309928 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100311360 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1002cdfac - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1002d8648 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a2634 - /private/va
: CFRunLoopRunSpecific
	0x1d6a681a8 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1941f090c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1942a49d0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1000505f4 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : xamarin_UIApplicationMain
	0x1003a2668 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1003a0f68 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100395974 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x100393540 - /private/var/
tzCore : <redacted>
	0x193225028 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19326ed7c - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x193e9fff4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9d76c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9d3b0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193e9e254 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x191bbb834 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bbb7c8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb92f8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb8484 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x191bb7cd8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation 
ion
	0x10037cccc - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x10035f04c - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollection
	0x1ee986e9c - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x193dfdc3c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193dfdb44 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193dfdab8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x193df6b10 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1932553b4 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x193254f38 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x1932b00e0 - /System/Library/Frameworks/QuartzCore.framework/Quar
n <0x00536>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x000bc>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0007e>
	  at <unknown> <0x00000>
=================================================================

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

An error has occurred in the native fault reporting. Some diagnostic information will be unavailable.

=================================================================
	Native stacktrace:
=================================================================
	0x100391de0 - /private/var/containers/Bundle/Application/2157AA24-E58D-40BB-B68A-9FD8939C6462/AppPdfTest.app/Xamarin.PreBuilt.iOS : AppleCryptoNative_X509ImportCollect

**Comment by vitalii-vov** [comment]
Hello,
At first glance, it is not clear what the problem might be. 
But maybe the problem is related to the use of Hot Reload.

**Comment by vikashhd** [comment]
Seems like it related to Hot Reload. I will try to check in release mode.

**Comment by vikashhd** [comment]
@vitalii-vov  yes culprit is Hot Reload. Nothing related to PDFView, we can close it. Thanks
