### ISSUE TITLE
PDFView inside scrollView

### ISSUE THREAD

**Issue by nk-alex** [vitalii-vov/Maui.PDFView#5]
This is my case:

I have a large vertical StackLayout inside a ScrollView. One of the elements of this StackLayout is a PDFView. The problem I'm facing is zooming and moving around the PDFView (move up&down) causes the ScrollView to scroll.

If no zooming factor is applied over the PDFView, the scrolling behaviour works as expected.

Is there anyway to prevent this behaviour?

**Comment by vitalii-vov** [comment]
Is this repeated for all platforms?

`PDFView` uses `ScrollView` internally to display data. You are trying to put one `ScrollView` inside another `ScrollView`, which will naturally cause a problem.

You could try calculating the height of the `PDFView` based on the number of pages and try playing with the `HeightRequest` parameter of the `PDFView` to give it a fixed height.

But I think you should redesign your window, e.g. using tabs and placing PDF content in a separate tab, which would avoid conflict with `ScrollView`.
