### ISSUE TITLE
PDFView crashes on invalid PDF

### ISSUE THREAD

**Issue by breyed** [vitalii-vov/Maui.PDFView#6]
If the PDF being viewed is invalid, `PdfRenderer` throws `Java.IO.IOException` with the message "file not in PDF format or corrupted". `RenderPages` should catch this exception. A simple fallback is to just not render any pages. Even better would be to display an error.

**Comment by vitalii-vov** [comment]
`RenderPages` can catch an exception, but only if we don't want to throw the original platform exceptions and prefer to throw our custom exception instead.

Suppressing exceptions will prevent you from debugging the application, and you won't understand why the PDF file pages are not displayed. This is bad practice and should not be followed.

You must provide a valid path. If you are unsure of the path, you should verify it before passing it to `PdfSource`.

If you cannot verify the path, just use try-catch, for example:

```csharp
internal partial class MainPageViewModel : ObservableObject
{
    [ObservableProperty] private string _pdfSource;

    [RelayCommand] private void ChangeUri()
    {
        try 
        {
            PdfSource = "/path/to/file.pdf";
        }
        catch(Exception ex)
        {
             // handle exception
        }
    }
}
```
